# Generated by Django 2.2 on 2019-05-27 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='campaign',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='item.MarketingCampaign'),
        ),
    ]
